#pragma once



#include <vector>
#include <algorithm>


typedef unsigned char Byte;
typedef std::vector<Byte> Buffer;



#define SUCCESS 1
#define FAIL 0

#define DISCONNECT -1

enum RequestId {
	SIGNUP_REQUEST = 1, LOGIN_REQUEST, LOGOUT_REQUEST, CREATEROOM_REQUEST, JOINROOM_REQUEST, GETROOMS_REQUEST, HIGHSCORE_REQUEST, GETPLAYERSINROOM_REQUEST,
	CLOSEROOM_REQUEST, STARTGAME_REQUEST, GETROOMSTATE_REQUEST, LEAVEROOM_REQUEST, LAST_ENUM
};

enum ResponseId {
	ERROR_RESPONSE = LAST_ENUM, SIGNUP_RESPONSE, LOGIN_RESPONSE, LOGOUT_RESPONSE, CREATEROOM_RESPONSE, JOINROOM_RESPONSE, GETROOMS_RESPONSE, GETPLAYERSINROOM_RESPONSE, HIGHSCORE_RESPONSE,
	CLOSEROOM_RESPONSE, STARTGAME_RESPONSE, GETROOMSTATE_RESPONSE, LEAVEROOM_RESPONSE
};